name: Deploy Python Flask App to Azure Web App

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

            - name: Azure Login
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Deploy infrastructure with Bicep
              uses: azure/arm-deploy@v1
              with:
                subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
                template: ./infra/main.bicep
                parameters: |
                  appName=${{ secrets.AZURE_WEBAPP_NAME }}

            - name: Archive code
              run: zip -r release.zip . -x '*.git*'

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v3
              with:
                app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
                publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
                package: release.zip